import "./globals.css";
import { Inter } from "next/font/google";

import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="p-4">
          <Header />
          
          <section className="flex gap-4">
            <Sidebar />
            <main className="pl-4 border-l pb-4">{children}</main>
          </section>

          <footer className="text-sm py-4 border-t text-gray-600 text-center">&copy; Copyright 2024</footer>
        </div>
      </body>
    </html>
  );
}
